### ISSUE TITLE
Suggestion: Levels Support

### ISSUE THREAD

**Issue by txm3278** [caewok/fvtt-elevated-vision#25]
Use case would be for a cave (basement layer with levels) where certain parts of the cave are elevated. Right now Elevation marks all layers and doesn't allow elevations less than 0. Also lighting placed on a specific level does not appear when using this module.

**Comment by caewok** [comment]
Actually, there are settings in each scene setting to tell Elevated Vision what minimum elevation you want, and what step size for elevation you want. So if you have a scene with a basement layer, set the minimum to whatever your lowest value is. 

Elevated Vision should otherwise work with Levels.

Note that at the moment, changing the step size or minimum elevation will change any existing elevations in the scene. I am working on improving that. https://github.com/caewok/fvtt-elevated-vision/issues/23

**Comment by txm3278** [comment]
The last sentence I believe still applies? I have a map with 2 layers, one at 0, one at -30. This is the vision of a character with elevated vision enabled (No terrain has been elevated):
![image](https://user-images.githubusercontent.com/25332081/197426270-51179720-2085-4265-8444-9e396e92b51a.png)
This is with elevated vision disabled:
![image](https://user-images.githubusercontent.com/25332081/197426344-ea675bb7-ffc5-4687-9071-fd5b96a28247.png)

**Comment by txm3278** [comment]
I also have Adequate Vision installed (probably too many vision based modules) but disabling that one doesn't fix the issue.
