### ISSUE TITLE
Vision broken when used with levels and perfect vision

### ISSUE THREAD

**Issue by txm3278** [caewok/fvtt-elevated-vision#26]
I have a map with 2 layers, one at 0, one at -30. Vision works fine on the base layer (0 elevation) but doesn't on any other level. I'm using both levels and perfect vision.
This is the vision of a character with elevated vision enabled (No terrain has been elevated):
![image](https://user-images.githubusercontent.com/25332081/197426270-51179720-2085-4265-8444-9e396e92b51a.png)
This is with elevated vision disabled:
![image](https://user-images.githubusercontent.com/25332081/197426344-ea675bb7-ffc5-4687-9071-fd5b96a28247.png)

**Comment by caewok** [comment]
Thanks for this report. The short answer is that, for the given scene, you will need to set the minimum elevation in the scene settings to be equal or less than the minimum elevation you are using in Levels.

In the Scene Configuration, you should see an Elevated Vision box at the bottom. Change the Minimum Elevation to the minimum for the scene that you intend to use with Levels. (For the above images, this is probably -30.) Sorry, but at the moment, changing the Minimum Elevation will cause any elevations in the scene to change (issue #23). WIP. 

I will think about ways to make this more obvious. I don't see an easy way to tell when the minimum scene elevation is changed in Levels, and so I don't want to just constantly check if this value has changed (which it rarely will).

**Comment by caewok** [comment]
I take it back... there is something else happening with Levels such that setting the minimum elevation for the scene is not always sufficient to fix the problem... Will look into it.

**Comment by caewok** [comment]
Fixed in v0.1.6. One caveat, however --- I think this requires you set the elevation for the terrain in and around the basement to the level of the basement. So if your cave above is at -30 and you are using a tile with Levels with a bottom range of -30, you should set the elevation of the terrain around the basement to -30 as well. 

Alternatively, turning off "Apply elevation data to token vision" will correct the issue, because it is specific to how the vision shader works when that toggle is on.
