### ISSUE TITLE
Can only change elevation in increments of 2.

### ISSUE THREAD

**Issue by sroakjp** [caewok/fvtt-elevated-vision#72]
No matter what I change the default elevation increment in the settings, or what I change the level increment in the elevation box next to the menu, it always reverts to increments of 2, 4 etc. I'm not getting any error messages.

**Comment by sroakjp** [comment]
I've tried changing the value here:
![image](https://github.com/caewok/fvtt-elevated-vision/assets/62338951/74090554-a9e5-406b-84d5-d31a230b96c2)
And here:
![image](https://github.com/caewok/fvtt-elevated-vision/assets/62338951/ea0e4ea9-acbe-4c37-86a2-bd3b1cdfa7ac)

**Comment by caewok** [comment]
I am not seeing this. I did make some tweaks so that changing the elevation increment in the scene settings should cause the value in the control to switch to the nearest multiple. (Before, it was not changing until you clicked on an arrow.) But I have never seen it get stuck on a specific value. Are there any other modules enabled besides libWrapper and Wall Height?

**Comment by sroakjp** [comment]
User error. I had not noticed that there is a scene specific setting, under the scene configuration, that overrides the global setting. I changed this, and all is fixed.

![image](https://github.com/caewok/fvtt-elevated-vision/assets/62338951/b3515376-43b4-4ae0-9841-cc67981e8e55)
