### ISSUE TITLE
Walls cast shadows towards the light

### ISSUE THREAD

**Issue by rapus95** [caewok/fvtt-elevated-vision#92]
Trying to design a point source which has shadows cast away from the center of the map. Doing that, I encountered the following situation which looks wrong:
![image](https://github.com/caewok/fvtt-elevated-vision/assets/5960902/246c7d1d-345a-4772-8ef7-04e88097e67f)

**Comment by caewok** [comment]
Can you right click on the scene in the scenes tab, click Export Data, and then upload that JSON here? Also, what are your light configuration settings?

**Comment by rapus95** [comment]
[fvtt-Scene-ruins-of-caradoon-GnbM07rna6pUdhiW.json](https://github.com/caewok/fvtt-elevated-vision/files/13062156/fvtt-Scene-ruins-of-caradoon-GnbM07rna6pUdhiW.json)
![image](https://github.com/caewok/fvtt-elevated-vision/assets/5960902/7a3eaee2-bd53-4bc9-a767-c37f7a59bc18)
![image](https://github.com/caewok/fvtt-elevated-vision/assets/5960902/0c113778-bd0e-42f5-a6a7-d8ab64b2a6e7)
do you need anything else?

**Comment by caewok** [comment]
A few thoughts:

1. Yes, I would expect some trouble with the Limits module. Technically, Elevated Vision doesn't mess with lights per se, just shadows. But I am sure there are some interaction issues, because Elevated Vision has to meddle quite a bit with lighting and token vision. 

2. Does it look better in v0.5.10? I killed some bugs that might have made a difference. When I display your scene with just Elevated Vision, Wall Height, and libWrapper enabled, it looks pretty decent. (This is without any terrain elevation set, just using the limited-height walls for the shadows.)
![Screenshot 2023-10-22 at 4 27 05 PM](https://github.com/caewok/fvtt-elevated-vision/assets/1267134/66d895f0-3bc4-41bc-a080-5fbc4a7391b6)

3. You might also using a directional light instead of the 1000' light. Depends a lot on what you are going for, but directional lights were made for this sort of elongated shadow effect. The directional shadows will create parallel shadows (because the light is assumed to be infinitely far) and more closely mimics shadows from sunlight. Note the differences in this screenshot, where the sun is set to be overhead slightly southwest, causing all the shadows to go northeast. 
![Screenshot 2023-10-22 at 4 20 06 PM](https://github.com/caewok/fvtt-elevated-vision/assets/1267134/d495c38a-cb7e-4c23-bb9c-b3d1a9ca3f36)

**Comment by rapus95** [comment]
it looks like some directional issue (normals, signs etc):
source is bottom right of walls -> correct shadows
![image](https://github.com/caewok/fvtt-elevated-vision/assets/5960902/1c2c00af-ace2-4d52-b1d4-fd26826f7bfb)
source is top left of the walls -> failing shadows
![image](https://github.com/caewok/fvtt-elevated-vision/assets/5960902/1461d3ea-37b1-4936-b0b4-2c1539b6449e)

**Comment by rapus95** [comment]
but another player couldn't recreate the issue in their browser 🥲

**Comment by caewok** [comment]
Closing as I cannot fix graphics driver bugs, which is what this sounds like.
